CREATE TABLE perks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    build_id INTEGER 
        REFERENCES builds(id) ON DELETE CASCADE NOT NULL,
    stat_title TEXT NOT NULL,
    stat_rank INTEGER NOT NULL,
    perk_rank INTEGER NOT NULL,
    perk_description TEXT NOT NULL
)